### ISSUE TITLE
Queue Name missing on Call Distribution section

### ISSUE THREAD

**Issue by sjackson0109** [mozziemozz/M365CallFlowVisualizer#12]
Queue name should go here:
![image](https://user-images.githubusercontent.com/38080190/151978103-7bfc011d-bcc1-4953-80d3-68c603ca2c01.png)

**Comment by mozziemozz** [comment]
CQ Name is already in Agent List subgraph. What do you suggest as agent list subgraph title, If i were to move the CQ Name to the call distribution subgraph?

<img width="597" alt="image" src="https://user-images.githubusercontent.com/50239556/151985376-7df03187-5ff9-4b51-8341-8b3c83ec8b23.png">

**Comment by sjackson0109** [comment]
i've got some examples but i feel it might be easier to show/demonstrate to you where these 'nested shapes' are not quite right.. and i think it stems down to where the shapes are linked from.

**Comment by mozziemozz** [comment]
I don't fully understand what you mean here. I thought this was just about displaying the CQs name as the subgraph title instead of "Call Distribution". What do you propose? Sharing marked up screenshots or a Teams Meeting?

**Comment by sjackson0109** [comment]
Teams meeting sounds good.

We can chat on ***@***.***

**Comment by mozziemozz** [comment]
Email address is hidden. I think you follow me on twitter, feel free to dm there.

**Comment by sjackson0109** [comment]
Got it :)

**Comment by mozziemozz** [comment]
Replaced subgraph title "Call Distribution" with the Call Queues name. Replace Agent List "Call Queue Name" with just "Agent List".

Moved call connected decision before timeout. I want to keep this decision in the diagram. If an agent answers the phone, the call is connected and the call does not travel any further in the call flow. If it doesn't get answered, it goes to the timeout. I like this much better than before, you were right, thanks.

I'm also keeping the CQ Settings on the left side because these settings or properties are things which impact the callers or the agents experience, while the call is ringing. E.g. MoH is being played back during call distribution. Or if Presence Based Routing is enabled, only available agents will get calls etc.

<img width="664" alt="image" src="https://user-images.githubusercontent.com/50239556/152409131-22dd0c94-a840-4b66-9ae1-34d66f3e2d5f.png">
