### ISSUE TITLE
Hide Greeting Note, if not set

### ISSUE THREAD

**Issue by sjackson0109** [mozziemozz/M365CallFlowVisualizer#13]
Drawing this shape is not necessary, if there is no note-text to render:
![image](https://user-images.githubusercontent.com/38080190/151979085-351968c5-7687-4861-bb48-952d1606db7e.png)

**Comment by mozziemozz** [comment]
I will look into that. I already do it with the system greeting. The idea was, that every greeting is shown, (even when it's not configured) as somebody which is not a teams admin might not know that it's possible to insert a greeting at these specific points in the call flow. It's also helpful for troubleshooting purposes. (E.g. should play greeting but was not configured etc...)

As the code is now fairly robust, I have to check how difficult it would be to not draw these nodes, because many times the greeting is the first node of a subsequent call flow. If I just remove it, and the previous link points to a nonexistent node, the diagram will break.

**Comment by mozziemozz** [comment]
Implemented in V 2.5.3
<img width="704" alt="image" src="https://user-images.githubusercontent.com/50239556/152408319-2d65b9a4-fca5-4402-b5e9-5251f2110378.png">
