### ISSUE TITLE
Holiday collapse/foldout

### ISSUE THREAD

**Issue by sjackson0109** [mozziemozz/M365CallFlowVisualizer#29]
Is it possible for you to collapse/click-to-expand sections of the diagram?
EG: click on a subgraph to collapse, click on the shape in situ to expand..

**Comment by mozziemozz** [comment]
I don't think that's possible with Mermaid. See here: https://github.com/mermaid-js/mermaid/issues/1123
You could run the script again for a nested AA/CQ with -ShowNestedCallFlows $false so that you get a standalone diagram for that AA/CQ if that makes it easier to read. With some extra work it might be possible to run the script for each nested AA/CQ and put click actions on the nested nodes so that clicking it will open the other htm file in the same directory. But I guess this would be quite hard to implement because of the current methods used in the script.
