### ISSUE TITLE
Error passing User Account ID for nested Call flows

### ISSUE THREAD

**Issue by fmustafa** [mozziemozz/M365CallFlowVisualizer#30]
Hi Martin, 
I am getting an error when generating the call flow diagram if it has Account Type "User Account" as shown in the attached screenshot. 

In the main script "M365CallFlowVisualizerV2.ps1" Line 3388 Function Get-NestedCallFlow, it performs check on $accountType, but it seems that it fails to pass the proper UserID to the next function "Get-TeamsUserCallFlow -UserId $nestedVoiceApp" (Line 3410). 

Any suggestions on this?

Thanks in advance for your help. 

![image](https://user-images.githubusercontent.com/545538/193024769-d1182e82-2d7b-4a05-b7b7-fca858e9721c.png)

**Comment by mozziemozz** [comment]
Hi,

Do the Auto Attendant and the user have the same Display Name? When it says "Voice App Id:" in the console output, then it should be the ID of a AA/CQ. When it's reading a user call flow it should say "User Id:" 

<img width="260" alt="image" src="https://user-images.githubusercontent.com/50239556/192942611-6fd365f2-7664-4bc6-a960-7544059d9b8a.png">

Please run the script with dot sourcing like this:
`. .\M365CallFlowVisualizerV2.ps1`
When it fails/finishes you will be able to check the $nestedVoiceApps Array by entering this in the terminal. This should then include the ID of the user which is configured in this call flow. However, I suspect that you won't find the ID since it fails in your case. It also displays no User Id in your console output.

The first error is from Get-TeamsUserCallFlow Function on line 124 which is a simple Get-CsOnlineUser `$teamsUser = Get-CsOnlineUser -Identity $UserId` but the ID is not present.

Please check your AA in TAC if the user is indeed configured correctly. Maybe the user has been deleted or changed.

Are you using the latest Version 2.8.1? If not, please download it and try again.
Also can you tell me at which stage the user is configured? Is it AA Default Call Flow, After Hours Call Flow or CQ Timeout or Overflow?

Thanks.

**Comment by fmustafa** [comment]
Hi Martin, Thanks for your prompt update.

I found another AA account causing the same issue. If I understand you correctly, what you mean is that the issue is definitely with the accounts and not the script passing the IDs. 

I checked the naming and properties of both accounts and their related AA and they match. 

![image](https://user-images.githubusercontent.com/545538/193147880-19270c15-2325-4b77-9e66-91557b017ec7.png)

Thanks again for your help.

**Comment by mozziemozz** [comment]
Hi Mustafa,

You need to check the value of $nestedVoiceApps not $nestedVoiceApp.

I can't say it for sure. It's just a guess. Can you try to run it with the parameter:

-ShowUserCallingSettings $false

To see if it works without expanding user calling settings.

Where in the Call Flow does the AA forward to the user? Default, or after hours call flow? Can you maybe share a screenshot of the TAC configuration?

Thanks.

**Comment by mozziemozz** [comment]
I think I know what the problem is. It looks like somehow the commands $allAutoAttendantIds and $allCallQueueIds on lines 288 and 289 do not work. Are you running to from PowerShell ISE or PowerShell console? I saw the error too on another user's PC using ISE. It works for me in VS Code.

Which Teams Module Version are you using?

**Comment by fmustafa** [comment]
I run it from a PowerShell console. 

Here are the versions:
![image](https://user-images.githubusercontent.com/545538/193284553-98a4d213-94f9-4b8c-a664-0b36717473d0.png)

**Comment by mozziemozz** [comment]
Thanks. Very strange. It works for mee too in PowerShell Console for an AA which has multiple Queues in an IVR.

How many Auto Attendants and Call Queues does your tenant have? Maybe there's an issue with the amount of AAs or CQs...

From what I can see, there's no Teams User involved in the AA, just Voice Apps / Call Queues, is that correct? You should never see "UserId:" in the console output if there's direct forwarding configured to a user.

What happens when you enter the following in the terminal? Do the variables have some IDs in them?

`$allAutoAttendantIds = (Get-CsAutoAttendant).Identity
$allCallQueueIds = (Get-CsCallQueue -WarningAction SilentlyContinue).Identity`

**Comment by sjackson0109** [comment]
Worked for me too when testing

**Comment by fmustafa** [comment]
Yes, they have a whole list for both variables. The following screen shows the total counts: 

![image](https://user-images.githubusercontent.com/545538/193335422-de1201a7-1b10-4b07-8856-c3c9c1acfb6d.png)

**Comment by mozziemozz** [comment]
Hi Mustafa,

I didn't know that Get-CsCallQueue was limited to only 100 records when used without the -First parameter.
[](https://learn.microsoft.com/en-us/powershell/module/skype/get-cscallqueue?view=skype-ps#parameters)

I've uploaded version 2.8.2 to the dev branch. Instead of retrieving all AAs and CQs at specific points in the script, I only read all AAs, CQs and RAs once at the beginning of the script using -First 1000. This should also improve the performance in general. Please download/pull/clone the new version from the dev branch and test it again. Looking forward to your feedback.

Regards,
Martin

**Comment by fmustafa** [comment]
Hi Martin, 
Good News! I tested the DEV script and it is working fully now. I am able to export all Call Flows (including the problematic ones) with no errors at all. 

Thanks Again for your time and help in getting this issue resolved. 

![image](https://user-images.githubusercontent.com/545538/194403529-0017f601-2b54-4db1-9f48-d85bb8fc3ffe.png)


Regards,
Mustafa

**Comment by mozziemozz** [comment]
Hi Mustafa, thanks for the quick feedback. I‘ll update the changelog aswell and merge it to main sometime.

Gesendet von Outlook für iOS<https://aka.ms/o0ukef>
________________________________
Von: fmustafa ***@***.***>
Gesendet: Thursday, October 6, 2022 9:38:34 PM
An: mozziemozz/M365CallFlowVisualizer ***@***.***>
Cc: martin heusser ***@***.***>; Comment ***@***.***>
Betreff: Re: [mozziemozz/M365CallFlowVisualizer] Error passing User Account ID for nested Call flows (Issue #30)


Hi Martin,
Good News! I tested the DEV script and it is working fully now. I am able to export all Call Flows (including the problematic ones) with no errors at all.

Thanks Again for your time and help in getting this issue resolved.

[image]<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F545538%2F194403529-0017f601-2b54-4db1-9f48-d85bb8fc3ffe.png&data=05%7C01%7C%7C4da45305b0394a15eede08daa7d25bf6%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C638006819166320402%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=YmuEF4pp9VZ4Bc91YIdkhwvXPGfVsPc%2Bfpn32OMBSLY%3D&reserved=0>

Regards,
Mustafa

**Comment by fmustafa** [comment]
Hi Martin, 
One small suggestion before you merge the DEV, is it possible for the script to incorporate the date and time in the Output files names? Something like the following: 

![image](https://user-images.githubusercontent.com/545538/194675502-9429776a-5359-4a2d-8764-f8c40b19f726.png)

Around line 3569: 
![image](https://user-images.githubusercontent.com/545538/194675566-56188b30-fd11-4be6-97f2-e882de779f17.png)


Thanks again for your help. 

Regards,
Mustafa

**Comment by mozziemozz** [comment]
Hi Mustafa, sorry I missed your comment. It would be possible for sure. I'm just not sure how much work this would require since the filenames are referenced quite a few times in the script. Would it also help if I set the default filepath to .\Output\CurrentDate ? I think this would be much easier. There's also another script which will create a markdown file which includes all call flows. I use this in combo with DocFx so I have a docs site (similar to MS Learn). If all files have a date in them, it makes it much harder to reference in other files...

**Comment by fmustafa** [comment]
No worries  Martin,  there are no hard requirements here. You can do it the way you think it will work for everyone. Having the export to a folder with the date still works for me. 

Thanks again for all your help.

**Comment by mozziemozz** [comment]
Hi Mustafa, I've updated the script in a manner in which it automatically creates a folder with today's date in MM-dd-yyyy as the default output path. I hope that works for you?
