### ISSUE TITLE
Exact permissions required

### ISSUE THREAD

**Issue by dinocaputo** [mozziemozz/M365CallFlowVisualizer#32]
Even as a Teams Service Admin I am getting the following prompt in a customer environment.  
![image](https://user-images.githubusercontent.com/32268083/200611778-25211269-e070-4855-bce5-92d9e9eea320.png)

What exact permissions beyond Teams Service Admin are required to allow this to work?  Assuming some Graph permission required?

**Comment by mozziemozz** [comment]
This is usually because the customer tenant has never used graph powershell before. Ask a global admin of the customer to run this: 

`Connect-MgGraph -Scopes "User.Read.All","Group.Read.All"`

It will then ask for the admin's permission to grant access to these scopes.

Once that's done, "Microsoft Graph PowerShell" will appear under Enterprise applications in the Tenants Azure AD.
![image](https://user-images.githubusercontent.com/50239556/200615337-f3700b2c-9a6c-4016-b3ee-b882525bf0d9.png)

These are the only permissions required from Graph by the visualizer. This allows Graph PS to read all users and groups. The Admin account signing into it, will also need User Admin Role (besides Teams Administrator). 

I hope that helps.

**Comment by dinocaputo** [comment]
Let me see if this is something the customer will allow.
I can't see any downsides to this unless you are aware of any?

**Comment by mozziemozz** [comment]
@dinocaputo no, I don't see any downsides. In fact, the permissions are only granted to the defined scopes. If you try a Set-MgUser* command for example, you would get an error. You need to include the scope and then consent again, for the new scopes.

Sooner or later, everybody has to adopt Graph PS because MSOnline and Azure AD will be deprecated by MS at some point. The first version of the Visualizer was using MSOnline but because of community feedback I migrated to Graph PS quite a while ago.
