### ISSUE TITLE
Get-CsAutoAttendant sytax typo found

### ISSUE THREAD

**Issue by asi-nfigueroa** [mozziemozz/M365CallFlowVisualizer#36]
The function 'Find-CallQueueAndAutoAttendantUserLinks.ps1' has a syntax error on line 44:

`(Get-CsAutoAttendant- First 1000).Identity`

should be:

`(Get-CsAutoAttendant -First 1000).Identity`

After changing the formatting on my copy, the function worked perfectly.

**Comment by mozziemozz** [comment]
Thanks for pointing that out. There is now a seperate function to retrieve all AAs, CQs and Resource Accounts here: https://github.com/mozziemozz/M365CallFlowVisualizer/blob/main/Functions/Get-AllVoiceAppsAndResourceAccounts.ps1

This is more robust than -First 1000 because it gets all voice apps not just the first 1000 (if there are more than 1K). I'll update the FindUserLinks Function to use that function too when I get a chance.

**Comment by mozziemozz** [comment]
I updated the script to use the new function mentioned in my first comment on this issue. Also added the -CacheResults $true param when the M365CallFlowVisualizer.ps1 runs for each voice app. This should speed things up quite a bit.
