### ISSUE TITLE
QC Section - too many cylinder shapes - bloats the diagram unnecessarily

### ISSUE THREAD

**Issue by sjackson0109** [mozziemozz/M365CallFlowVisualizer#4]
Regarding the "QC Settings" section.. (call distribution/yellow block), all the settings could all be rendered in one shape; prefer a rectangle not the cylinder.

Music On Hold
Conference Mode Enabled
Agent Opt-Out Allowed
Presence Based Routing

etc..

Keep the Routing Method, Alert-time and Timeout as they are.. they work really well with the relationships.

**Comment by mozziemozz** [comment]
What do you think about this?
The cylinder shape is described as "Database" in Mermaid. So I figuered it's best suited because it stores/displays the value of the settings. Also I think it looks best like this.
<img width="562" alt="image" src="https://user-images.githubusercontent.com/50239556/149136472-6304deb7-8d70-4764-8a3f-ea1cd994d6b1.png">

**Comment by mozziemozz** [comment]
You can always fork it or create a pull request. For now, I was just making it to my liking. It's only been published and gaining traction for a few weeks now. I haven't thought about working with other contributors just yet.

Like I said, cylinders represent databases in Mermaid. Since they store the CQ properties I just thought they suit best. You can see all the available node shapes here: https://mermaid-js.github.io/mermaid/#/flowchart?id=node-shapes
So if you want other node shapes, you have to replace the existing syntax inside the script. But some node shape syntax is also linked to If conditions so a general search + replace might break the code... 

Right now, it's only possible to define custom colors for all the nodes fill. But in theory it would be possible to make each node a different color. This would get very complex, I suppose.

I'm glad it helps you save time.

**Comment by sjackson0109** [comment]
Absolutely respect you taking caution with contributions. I’ll consider forking at a later date, when am not under pressure for other projects at work.

So; do mermaid nodes have a class attribute that can be set; usually that’s how colours/sizes etc can be set centrally (think CSS)?  I’ll do some further reading. 

Have you considered doing the file-push straight to mermaid.live and automatically outputting the PNG to disk ?  Saving the user doing this manually?  Diagrams could then be orchestrated via a scheduled task of some kind.

**Comment by mozziemozz** [comment]
I have no idea about web development technologies tbh. It was all just trial and error so far. I think mermaid does support css but I don't know how it works. I figured out, that you can set a theme inside markdown by adding the following:
`%%{init: {'theme': 'default', "flowchart" : { "curve" : "basis" } } }%%`
above the flowchart TB in a markdown file. "default" can also be dark, neutral or forest, these are supported.

But you can also customize it if you leave this line out. When you use -Theme custom with my script, you can specify color codes for node fill, border, font color, link color and link text. This adds the following after the diagram:
`classDef customTheme fill:#87bd40,stroke:#ffffff,stroke-width:3px,color:#ffffff`

You then add another line `class nodeid1, nodeid2 customTheme`. This means that the custom colors will get applied to nodeid1 and nodeid2. Link colors are a little bit trickier because they are only using numbers. So if you want to color just one link differently you have to know which exact number (starting at 0) it has in the diagram. This is nearly impossible to do because each diagram can have a different amount of links in it based on the callflow connections in M365.

I suggest you try to run the script with -Theme default and -Theme custom and compare the Markdown outputs to see how it works.

Regarding the PNG output. It seems like it doesn't work very well with PNG because there is a lot of blank content added on top and below the diagram. If it's a complex call flow, the png is bearely readable. SVG works much better. But I have not found a way to directly export to SVG. I was trying mermaid CLI but I always got errors. I don't think it supports flowchart yet. Only Graph but with Graph, I couldn't draw the diagram as I liked / it is now.

Do you think it's possible to do an API call to Mermaid.live with the scripts output? I haven't seen a way to do that yet.

The best I was able to achieve is to output directly to *.htm file instead of Markdown or Mermaid. This was added in V 2.4 and can be used with -ExportHtml $true. This way, you'll also get an htm file which can be opened in any modern browser.

With the "helper script" AllTopLevelVoiceAppsToMarkdown.ps1" (also in the Repo) I can now loop through all Voice Apps which have a Phone Number assigned and automatically generate Markdown and htm files for 1 customer. I need markdown because this will be included in a DocFx Documentation site. I need htm so a user can click on it and view it larger if the diagram is too small within DocFx. The htm file can also be right clicked and downloaded.

Please see the attached example of an htm output file. Maybe that helps too? (Since it can be opened by anyone with a modern browser and no coding skills or manual steps (copy/paste) are required.

[PS_Test_CQ_CallFlow.zip](https://github.com/mozziemozz/M365CallFlowVisualizer/files/7861325/PS_Test_CQ_CallFlow.zip)

**Comment by sjackson0109** [comment]
HTML looks good.

Plz merge "Routing Method" and "Agent Alert Time" into the first CQ Settings shape.

Looks mermaid.live supports styling.. am happy to play with that later.


You have a shape (diamond) where it reads "Call Connected" > Yes/No.  The YES action should proceed to "End", not "Call Connected".

Check the name in your last shape, you may want to remove that ZIP from the previous post.

Feel free to mark this as resolved.

**Comment by mozziemozz** [comment]
Yeah no worries, this is all from my Test/Demo Tenant. "Axe Cap" is a fictional firm from the TV Show Billions. All my test users are also named after characters from there. It's much easier to work with names instead of Test User 1,2 etc. in Test environments imo.

> You have a shape (diamond) where it reads "Call Connected" > Yes/No. The YES action should proceed to "End", not "Call Connected".

I disagree. If an Agent Takes a call, the caller is connected on the phone. To me, "End" only applies in scenarios, where an AA or a CQ would terminate a call after e.g. a greeting message has been played back. From my POV if a call enters a call flow, there are only 3 outcomes: Disconnect, Connected to Agent or forwarded to External PSTN and I think that should be reflected in the graph.

Currently, each "sub call flow" or even descicions in sub call flows have their own End/Connected nodes. I thought about interlinking all of them into one, as it's now the case with users, AAs, CQs, external numbers (except for the holiday graphs). But I suppose this would create way too much links and link overlapping which would make the diagram much more difficult to read...

I will close the issue, feel free to contact me on twitter or LinkedIn for further discussions. I appreciate the feedback.

**Comment by mozziemozz** [comment]
One more thing, I want to keep the agent alert time a separate node for now. I might add support for serial routing at some point. For this I would insert an Agent Alert Time Node between every agent.
