### ISSUE TITLE
Syntax Error in marmaid if callqueue "Time out" time is set to 0

### ISSUE THREAD

**Issue by DeMikey** [mozziemozz/M365CallFlowVisualizer#40]
Syntax Error in marmaid if callqueue "Time out" time is set to 0
![image](https://github.com/mozziemozz/M365CallFlowVisualizer/assets/37411507/7b8fdb5e-1790-4048-a0ff-984035047e9a)

![image](https://github.com/mozziemozz/M365CallFlowVisualizer/assets/37411507/eb9fbe7f-1c2a-4557-8b7c-2d71d380122a)

**Comment by mozziemozz** [comment]
Hi,

This is most likely caused by something else. It works fine for me. 

<img width="298" alt="image" src="https://github.com/mozziemozz/M365CallFlowVisualizer/assets/50239556/7a9ec6ac-8f16-4dda-8e87-025ebb6d5d02">

Please try to copy the mermaid diagram and paste it on https://mermaid.live. This will tell you on which line the syntax error occurs.

Also, what parameters are you using? Are you showing TTS greetings? Sometimes TTS greetings include characters which cause syntax errors in mermaid and are not yet handled by the Optimize-DisplayName function.

Thanks

**Comment by DeMikey** [comment]
Hi
Thanks for your tip. I was able to find the error, it is a formatted external phone number:
(TransferCallToTarget) --> +41 79 xxx xx xx(External Number <br> +41 79 xxx xx xx)

**Comment by mozziemozz** [comment]
So do you still get the error? the node Id (phone number before brackets shouldn't contain any white spaces... unless something has changed on how phone numbers are stored on AAs/CQs.

Try to enter the phone number again in TAC, save and rerun the script. If the error still persists, I can try to repro and fix it but I generated a diagram which forwards from AA to external number just last week and it worked fine.

Gesendet von Outlook für iOS<https://aka.ms/o0ukef>
________________________________
Von: DeMike ***@***.***>
Gesendet: Sonntag, November 26, 2023 16:47
An: mozziemozz/M365CallFlowVisualizer ***@***.***>
Cc: Martin Heusser ***@***.***>; Comment ***@***.***>
Betreff: Re: [mozziemozz/M365CallFlowVisualizer] Syntax Error in marmaid if callqueue "Time out" time is set to 0 (Issue #40)


Hi
Thanks for your tip. I was able to find the error, it is a formatted external phone number:
(TransferCallToTarget) --> +41 79 xxx xx xx(External Number
+41 79 xxx xx xx)
