### ISSUE TITLE
Line 5288 - Cannot bind argument to parameter 'ReferenceObject' because it is null

### ISSUE THREAD

**Issue by WLeishmanCyAs** [mozziemozz/M365CallFlowVisualizer#41]
```
Compare-Object: .\M365CallFlowVisualizer-main\M365CallFlowVisualizer-main\M365CallFlowVisualizerV2.ps1:5288
Line |
5288 |      if (Compare-Object -ReferenceObject $nestedVoiceApps -DifferenceO …
     |                                          ~~~~~~~~~~~~~~~~
     | Cannot bind argument to parameter 'ReferenceObject' because it is null.
```

**Comment by mozziemozz** [comment]
Please provide more info. Does this happen for all call flows or only one? Please manually check all nested voice apps in TAC and confirm that they are configured correctly. Sometimes this happens when e.g. a linked resource account of a voice app was deleted.

**Comment by sjackson0109** [comment]
I had a similar error when a call queue had a security group assigned, but it was deleted via the azure portal. A simple restore from the deleted items view and then it all worked after just 5minutes.On 20 Feb 2024, at 03:01, Martin Heusser ***@***.***> wrote:﻿
Please provide more info. Does this happen for all call flows or only one? Please manually check all nested voice apps in TAC and confirm that they are configured correctly. Sometimes this happens when e.g. a linked resource account of a voice app was deleted.

**Comment by WLeishmanCyAs** [comment]
> Please provide more info. Does this happen for all call flows or only one? Please manually check all nested voice apps in TAC and confirm that they are configured correctly. Sometimes this happens when e.g. a linked resource account of a voice app was deleted.

Yes, not all call flows, simple ones that are no calling other AA or CQ's seem to report fine... seems to be the higher top level flows with other nested AA or CQ's for a couple different clients.  I've confirmed all Resource accounts are active although we don't have phone #'s tied to many of them (just resource account licenses).  I've confirmed every flow has an active Voice App or  User tied to every call flow option.

**Comment by sjackson0109** [comment]
What about holiday entries…On 20 Feb 2024, at 16:02, WLeishmanCyAs ***@***.***> wrote:﻿

Please provide more info. Does this happen for all call flows or only one? Please manually check all nested voice apps in TAC and confirm that they are configured correctly. Sometimes this happens when e.g. a linked resource account of a voice app was deleted.

Yes, not all call flows, simple ones that are no calling other AA or CQ's seem to report fine... seems to be the higher top level flows with other nested AA or CQ's for a couple different clients.  I've confirmed all Resource accounts are active although we don't have phone #'s tied to many of them (just resource account licenses).  I've confirmed every flow has an active Voice App or  User tied to every call flow option.

**Comment by WLeishmanCyAs** [comment]
> What about holiday entries…>

We've removed all Holiday Entries (all were past years anyhow, had not updated for 2024)

**Comment by WLeishmanCyAs** [comment]
We do have Voice Apps in some of the nested AutoAttendants to go back to the "Main Menu", which calls the AA that the Nested one spawned from.

**Comment by sjackson0109** [comment]
Perhaps,Look at the AA via the TAC webpage, clicking next , and looking at each and every sub-menu. Ensure you click Ok or next. That will force validation to kick on.If there was a null reference somewhere, you should find it.I strongly believe this isn’t a coding issue with m365callflowvisualizer. The error comes from Microsoft’s API.On 20 Feb 2024, at 17:10, WLeishmanCyAs ***@***.***> wrote:﻿
We do have Voice Apps in some of the nested AutoAttendants to go back to the "Main Menu", which calls the AA that the Nested one spawned from.

**Comment by mozziemozz** [comment]
Thanks @sjackson0109 for providing these tips. I agree, it's usually a misconfiguration somewhere in the call flow. The function to read the nested voice apps or user settings recuriavely has been working for forever and since noone else has reported any issues and it works for others, I beleive it must be something in your config...

**Comment by WLeishmanCyAs** [comment]
I've gone through every AA and rebuilt each submenu item.  Seems to be something jacked with this Tenant that I'll probably need to escalate to MS... When I run the Auto Attendant Troubleshooter it tells me  "Required licenses are missing. Ensure the **Phone System–Virtual User** license has been enabled on the resource account."  The one I'm working on now happens to be a GCC Tenant and every resource account is already assigned a proper "Microsoft Teams Phone Resource Account for GCC" which should be working.  Love MS... not.

**Comment by mozziemozz** [comment]
So did the visualizer script work after rebuilding the AAs?

**Comment by WLeishmanCyAs** [comment]
Closing this 

> So did the visualizer script work after rebuilding the AAs?

Not at all, failed in exactly the same spot

**Comment by chrismooredev** [comment]
My organization is also hitting this original issue on one of the first call flows we're building out. We're happy to see this kind of tool exists so we can visually inspect them after they're built. :) Thanks!

I traced this down to https://github.com/mozziemozz/M365CallFlowVisualizer/blob/9066ca1a1d7db0e2b6b0e2e593e29583648e900b/Functions/Get-TeamsUserCallFlow.ps1#L1050 adding a null/empty string value to `$nestedVoiceApps`.

I believe this is from earlier lines assuming that `$forwardingTargetType` (derived from the `ApplicationId`) is valid, even when its not. This also manifests **as a compile error in the output mermaid**, as `$unansweredUserTargetVoiceAppId` is null, and thus no node name is output.

https://github.com/mozziemozz/M365CallFlowVisualizer/blob/9066ca1a1d7db0e2b6b0e2e593e29583648e900b/Functions/Get-TeamsUserCallFlow.ps1#L1046

```
$user = Get-CsOnlineUser -Identity VoiceUser@contoso.com
$callsettings = Get-CsUserCallingSettings -Identity $user.Identity
$unanswered_target = $callsettings.UnansweredTarget.Replace("sip:","")
Get-CsOnlineApplicationInstance -Identity $unanswered_target | Format-List

ApplicationId     :
DisplayName       : TargetUser
ObjectId          : yyyyyyyy-yyyy-yyyy-yyyy-yyyyyyyyyyyy
PhoneNumber       :
TenantId          : xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
UserPrincipalName : TargetUser@contoso.com
```

I'm not sure if a blank ApplicationId is correct... it feels like an MS bug but I'm not confident on my knowledge of the backend side of this stuff.

**Comment by mozziemozz** [comment]
If the lines which you mentioned are executed, it means that your call flow at some point forwards to a Teams user which forwards to either a call queue or an auto attendant which likely doesn't exist anymore.

Can you identify the user id of this user? You should be able to get the id from the script output. Then check this user either in Teams client, TAC or via `Get-CsUserCallingSettings` and see what's configured as unanswered target.

If that output where the ApplicationId is empty is from `Get-CsOnlineApplicationInstance` there's definitely something wrong with that resource account. I suggest to delete it and recreate it. The ApplicationId is always `11cd3e2e-fccb-42ad-ad00-878b93575e07` for CQs and `ce933385-9390-45d1-9512-c8d228074e07` for AAs unless you use 3rd party voice apps like e.g. Luware or Landis queues etc.

I hope that helps. Otherwise, if you can we could do a remote session so I can live troubleshoot this.

You can also try the version from the dev branch. I recently made some changes there to `Get-TeamsUserCallFlow`.

Otherwise I would need to do a live troubleshooting session with you (if you can) where you share your screen...

**Comment by chrismooredev** [comment]
I think I got something..

When looking at the Resource Account attached to the Auto Attendant, it showed properly as an 'Auto Attendant' resource account type (voice app id?), but the option was greyed out.

![image](https://github.com/mozziemozz/M365CallFlowVisualizer/assets/35407569/fc35d907-9c1c-4884-b12a-ef8986b3008b)

I was able to temporarily remove the RA from the AA, and when I looked back at the RA the option was blank. I manually set it to 'Auto Attendant' and assigned it back to the AA, and the ApplicationId was filled back in :) 

![image](https://github.com/mozziemozz/M365CallFlowVisualizer/assets/35407569/c3e41ce1-2590-4a31-85c1-b4984edd74ab)

It seems the process is a bit finicky though, as I tested with a fresh RA and had to repeat the assignments a few times until the ApplicationId updated/the Resource Account saved in the UI across refreshes.

Anyway - After doing that process, the graphing for that call flow tree worked like a charm. Thanks!

**Comment by sjackson0109** [comment]
Yeah good old Microsoft…“Object not set to an instance of an object” :)On 28 Feb 2024, at 22:37, Chris Moore ***@***.***> wrote:﻿
I think I got something..
When looking at the Resource Account attached to the Auto Attendant, it showed properly as an 'Auto Attendant' resource account type (voice app id?), but the option was greyed out.
image.png (view on web)
I was able to temporarily remove the RA from the AA, and when I looked back at the RA the option was blank. I manually set it to 'Auto Attendant' and assigned it back to the AA, and the ApplicationId was filled back in :)
image.png (view on web)
It seems the process is a bit finicky though, as I tested with a fresh RA and had to repeat the assignments a few times until the ApplicationId updated/the Resource Account saved in the UI across refreshes.
Anyway - After doing that process, the graphing for that call flow tree worked like a charm. Thanks!

**Comment by WLeishmanCyAs** [comment]
I'm leaning towards a MS bug... I have 3 different clients on 3 completely different M365 Tenants (one GCC), completely different AA's and CQ's (some several levels deep, others pretty simple) and the script drops the same error on line 5288 on all of them.  I've gone through every RA, every App, on all of them with same error every time.

**Comment by mozziemozz** [comment]
If it's failing for all, it might be a bug in the script or something I haven't encountered before. I could check it out in a screen share session if you want/can.
