### ISSUE TITLE
Outside of Business Hours - action list

### ISSUE THREAD

**Issue by sjackson0109** [mozziemozz/M365CallFlowVisualizer#9]
I see you have an 'action list' during holiday periods; displayed horizontally (B in picture).. but when you view the same action-list during business hours, it's displayed vertically (A).

Can these (A) all be horizontal bound inside the rectangle (B), so it's easier to explain to people?

![image](https://user-images.githubusercontent.com/38080190/151970054-4a901ea3-d6b7-4536-85d2-54032c846ab1.png)

**Comment by mozziemozz** [comment]
This is by design. An Auto Attendant can have up to 20 Holidays so displaying each holiday horizontally was the only plausible way in my opinion.

It would be possible to display A horizontally but only if they are inside a subgraph. In Mermaid you can only change direction in a subgraph. But to do that, the Link from "Outside Business Hours" would then need to connect to the subgraph instead of the greeting node.

e.g. see here in the updated Agent list. Alert Time now links to subgraph and the subgraph links to Timeout.
<img width="612" alt="image" src="https://user-images.githubusercontent.com/50239556/151974351-1d5fcab9-5091-4afa-9916-22458162a9db.png">

However,  "A" is an example of one of your call flows where it stops after just 3 actions (Voicemail). So other configurations might have other nested AAs or Queues which would make the diagram quite wide (not just long), which I don't think is a good idea.

The actions on holiday call handlings are terminated inside the subgraph for a reason. Let's assume that a company only has 1 shared voicemail group and at every point in a call flow where it goes to VM it goes to the same voicemail node in Mermaid. Typically Call flows start with an AA and often they have holiday checks. So the holiday table is at the top of the flowchart. Voicemails on the other hand are mostly used at the end of a call flow (e.g. nobody from the queue picks up the phone). If holiday targets were interlinked you'd have a link from top to bottom in the diagram which makes it bearly readable.

All the other nodes are linked according to the flow of the call from top to bottom.

**Comment by sjackson0109** [comment]
From your explanation, I think you got mixed up with ‘holidays’ vs ‘business hours’.

**Comment by mozziemozz** [comment]
I understood that you want the actions of A to be displayed the same way like the holiday actions in B, correct?

**Comment by sjackson0109** [comment]
sorry mixing up my tickets. you are correct
